<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Amanda Kay Montoya">

<title>Linear Regression as a Simple SEM</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="04 - Linear Regression as SEM_files/libs/clipboard/clipboard.min.js"></script>
<script src="04 - Linear Regression as SEM_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="04 - Linear Regression as SEM_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="04 - Linear Regression as SEM_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="04 - Linear Regression as SEM_files/libs/quarto-html/popper.min.js"></script>
<script src="04 - Linear Regression as SEM_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="04 - Linear Regression as SEM_files/libs/quarto-html/anchor.min.js"></script>
<link href="04 - Linear Regression as SEM_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="04 - Linear Regression as SEM_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="04 - Linear Regression as SEM_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="04 - Linear Regression as SEM_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="04 - Linear Regression as SEM_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linear Regression as a Simple SEM</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Amanda Kay Montoya </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>Load packages</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="outline" class="level1">
<h1>Outline</h1>
<ul>
<li>Simple linear regression (single outcome, single predictor)</li>
<li>Multiple linear regression (single outcome, multiple predictors)</li>
<li>Multivariate linear regression (multiple outcomes, multiple predictors)</li>
<li>Benefits of SEM?</li>
</ul>
</section>
<section id="simple-linear-regression" class="level1">
<h1>Simple Linear Regression</h1>
<section id="overview-simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="overview-simple-linear-regression">Overview Simple Linear Regression</h2>
<p><span class="math display">\[Y_i = b_0 + b_1 X_i + e_i\]</span> A simple regression shows how an outcome (<span class="math inline">\(𝑌_𝑖\)</span>) is related to a predictor (<span class="math inline">\(𝑋_𝑖\)</span>) through a linear function (<span class="math inline">\(𝑏_0+𝑏_1 𝑋_𝑖\)</span>), and remaining error (<span class="math inline">\(𝑒_𝑖\)</span>)</p>
<section id="interpretations" class="level3">
<h3 class="anchored" data-anchor-id="interpretations">Interpretations:</h3>
<p><span class="math inline">\(𝑏_0\)</span>: The predicted <span class="math inline">\(𝑌\)</span> for cases when <span class="math inline">\(𝑋\)</span> is zero</p>
<p><span class="math inline">\(𝑏_1\)</span>: For two cases that differ by 1 unit on <span class="math inline">\(𝑋\)</span>, the unit with the higher <span class="math inline">\(𝑋\)</span> is expected to be <span class="math inline">\(𝑏_1\)</span> units higher on <span class="math inline">\(𝑌\)</span></p>
</section>
<section id="ordinary-least-squares-ols" class="level3">
<h3 class="anchored" data-anchor-id="ordinary-least-squares-ols">Ordinary least squares (OLS):</h3>
<p>Used to select the values of <span class="math inline">\(𝑏_0\)</span> and <span class="math inline">\(𝑏_1\)</span> in a sample that <strong>minimize the sum of squared errors</strong> <span class="math display">\[𝑆𝑆𝐸=\sum^{N}_{i = 1}(𝑒_𝑖^2) =\sum^{N}_{i = 1}(𝑌_𝑖−𝑏_0−𝑏_1 𝑋_𝑖 )^2\]</span> OLS estimates of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> minimize this function.</p>
</section>
</section>
<section id="fitting-ols-in-r" class="level2">
<h2 class="anchored" data-anchor-id="fitting-ols-in-r">Fitting OLS in R</h2>
<section id="understanding-internalizing-symptoms-for-latinx-youth" class="level3">
<h3 class="anchored" data-anchor-id="understanding-internalizing-symptoms-for-latinx-youth">Understanding Internalizing Symptoms for LatinX Youth</h3>
<p>Delgadillo, D., Ramos, G., Montoya, A. K., Thamrin, H., Rapp, A., Escovar, E., &amp; Chavira, D. (2021). Discrimination and Internalizing Disorders in Rural Latinx Adolescents: An Ecological Model of Etiology. <em>Children and Youth Services Review</em>, <em>130</em>, 106250.</p>
<p>639 Latino students age 14 – 17 completed surveys on multiple measures</p>
<p><strong>Age</strong> (in years)</p>
<p><strong>Gender</strong> (Male/Female)</p>
<p><strong>Perceived Discrimination</strong>: 9 Items SAFE-C on a scale of 1-4</p>
<p><strong>Peer Victimization</strong>: 4 items Illinois Bullying Scale (IBS) on a scale of 1-4</p>
<p><strong>Familism</strong>: 7 items Familism Scale (FS) on a scale of 1-5</p>
<p><strong>Internalizing Symptoms</strong>: 31 items Youth Self Report (YSR) on a scale of 0-2.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>ramos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Ramos_Internalizing_nomissing.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ramos)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "PID"                 "Age"                 "Gender"             
 [4] "Dem10a"              "bully4"              "bully5"             
 [7] "bully6"              "bully7"              "bully_total"        
[10] "FS1"                 "FS2"                 "FS3"                
[13] "FS4"                 "FS5"                 "FS6"                
[16] "FS7"                 "FStot"               "safe1"              
[19] "safe2"               "safe8"               "safe10"             
[22] "safe13"              "safe15"              "safe16"             
[25] "safe20"              "safe21"              "safe_avg"           
[28] "internalizing_total" "ysr_prob_14"         "ysr_prob_29"        
[31] "ysr_prob_30"         "ysr_prob_31"         "ysr_prob_32"        
[34] "ysr_prob_33"         "ysr_prob_35"         "ysr_prob_45"        
[37] "ysr_prob_50"         "ysr_prob_52"         "ysr_prob_71"        
[40] "ysr_prob_91"         "ysr_prob_112"        "ysr_prob_5"         
[43] "ysr_prob_42"         "ysr_prob_65"         "ysr_prob_69"        
[46] "ysr_prob_75"         "ysr_prob_102"        "ysr_prob_103"       
[49] "ysr_prob_111"        "ysr_prob_47"         "ysr_prob_51"        
[52] "ysr_prob_54"         "ysr_prob_56a"        "ysr_prob_56b"       
[55] "ysr_prob_56c"        "ysr_prob_56d"        "ysr_prob_56e"       
[58] "ysr_prob_56f"        "ysr_prob_56g"        "ysr_prob_56h"       </code></pre>
</div>
</div>
</section>
<section id="does-discrimination-predict-internalizing-symptoms" class="level3">
<h3 class="anchored" data-anchor-id="does-discrimination-predict-internalizing-symptoms">Does discrimination predict internalizing symptoms?</h3>
<p><code>safe_avg</code> is the average of the SAFE scores</p>
<p><code>internalizing_total</code> is the sum of the internalizing items</p>
<p>How would we typically approach this question in a linear regression?</p>
<p><span class="math display">\[Y_i = b_0 + b_1 X_i + e_i\]</span></p>
<p>Where <span class="math inline">\(Y_i\)</span> is <code>internalizing_total</code>, and <span class="math inline">\(X_i\)</span> is <code>safe_avg</code></p>
</section>
<section id="descriptives" class="level3">
<h3 class="anchored" data-anchor-id="descriptives">Descriptives</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span>safe_avg, <span class="at">data =</span> ramos)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> min       Q1   median       Q3      max     mean        sd   n missing
   1 1.222222 1.444444 1.666667 3.777778 1.507511 0.4418774 585       0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span>internalizing_total, <span class="at">data =</span> ramos)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> min Q1 median Q3 max     mean       sd   n missing
   0  7     14 21  55 15.50256 10.77496 585       0</code></pre>
</div>
</div>
</section>
<section id="visualizing-the-relationship" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-the-relationship">Visualizing the relationship</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> safe_avg, <span class="at">y =</span> internalizing_total), <span class="at">data =</span> ramos)<span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04---Linear-Regression-as-SEM_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fitting-ols-in-r-1" class="level3">
<h3 class="anchored" data-anchor-id="fitting-ols-in-r-1">Fitting OLS in R</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>OLSsimple <span class="ot">&lt;-</span> <span class="fu">lm</span>(internalizing_total<span class="sc">~</span>safe_avg, <span class="at">data =</span> ramos)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(OLSsimple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = internalizing_total ~ safe_avg, data = ramos)

Residuals:
    Min      1Q  Median      3Q     Max 
-29.453  -7.171  -1.385   5.330  33.043 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -0.9698     1.4182  -0.684    0.494    
safe_avg     10.9269     0.9028  12.103   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.641 on 583 degrees of freedom
Multiple R-squared:  0.2008,    Adjusted R-squared:  0.1994 
F-statistic: 146.5 on 1 and 583 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="interpretations-inference" class="level3">
<h3 class="anchored" data-anchor-id="interpretations-inference">Interpretations &amp; Inference</h3>
<p><span class="math inline">\(\hat{b}_0\)</span> = -0.9697827</p>
<p>For individuals with a discrimination (SAFE) score of zero, their predicted number of internalizing symptoms is -0.97.</p>
<p><strong><em>NOTE:</em></strong> Zero is an impossible score on the SAFE scale, so this value is not particularly useful.</p>
<p><strong>Inference:</strong> The coefficient estimate is significantly different from zero (t(583) = -0.68, p = 0.494). Therefore we reject the null hypothesis that the population <span class="math inline">\(b_0\)</span> is equal to zero (i.e., we conclude it is not zero).</p>
<p><span class="math inline">\(\hat{b}_1\)</span> = 10.9268509</p>
<p>For two individuals who differ by 1 point on discrimination (SAFE) score, the person with the higher score (more discrimination) is predicted to be 10.93 higher in number of internalizing symptoms.</p>
<p><strong><em>NOTE:</em></strong> We do not use language like “change” or “increase” because in this study we did not directly observe changes or increases. Data is purely corelational. We are describing difference between people with different scores.</p>
<p><strong>Inference:</strong> The coefficient estimate is significantly different from zero (t(583) = 12.10, p &lt;.001). Therefore we reject the null hypothesis that the population <span class="math inline">\(b_0\)</span> is equal to zero (i.e., we conclude it is not zero).</p>
</section>
</section>
<section id="the-corresponding-sem" class="level2">
<h2 class="anchored" data-anchor-id="the-corresponding-sem">The Corresponding SEM</h2>
<p>We’ve established that the main equations for an SEM are</p>
<p><span class="math display">\[ \bf L = \alpha_L + BL + \epsilon_L\]</span> <span class="math display">\[ \bf Z = \alpha_Z + \Lambda L + \epsilon_Z\]</span></p>
<p>In a linear regression, there are no latent variables (<span class="math inline">\(\bf L\)</span>), so it may seem incompatible with SEM</p>
<p>However, we can assume <span class="math inline">\(\bf Z = L\)</span>, meaning that <span class="math inline">\(\bf Z\)</span> is a perfect representation of the latent variable (i.e., there is no measurement error)</p>
<p><span class="math display">\[ \bf Z = 0 + 1 L\]</span> Thus we assume <span class="math inline">\(\bf \alpha_Z = 0\)</span>, <span class="math inline">\(\bf \Lambda = I\)</span>, and <span class="math inline">\(\bf \epsilon_Z = 0\)</span></p>
<section id="simpler-sem-equation" class="level3">
<h3 class="anchored" data-anchor-id="simpler-sem-equation">Simpler SEM Equation</h3>
<p>Now we work directly with the following equation:</p>
<p><span class="math display">\[ \bf Z = \alpha + BZ + \epsilon\]</span></p>
<p>No need for the <span class="math inline">\(Z\)</span> subscript on <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\epsilon\)</span> because we only have <span class="math inline">\(Z\)</span> and no <span class="math inline">\(L\)</span>.</p>
<p>Let’s assume <span class="math inline">\({\bf Z} = \begin{bmatrix} X \\ Y \end{bmatrix}\)</span></p>
<p><span class="math display">\[{\bf \alpha} = \begin{bmatrix} \alpha_X \\ \alpha_Y \end{bmatrix}\]</span> <span class="math display">\[{\bf B} = \begin{bmatrix} 0 &amp; 0 \\ 1 &amp; 0 \end{bmatrix}\]</span> <span class="math display">\[{\bf \epsilon} = \begin{bmatrix} \epsilon_X \\ \epsilon_Y \end{bmatrix}\]</span></p>
</section>
<section id="separate-equations-for-x-and-y" class="level3">
<h3 class="anchored" data-anchor-id="separate-equations-for-x-and-y">Separate Equations for X and Y</h3>
<p>This gives us equations for <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span></p>
<p><span class="math display">\[X_i = \alpha_X + \epsilon_{Xi}\]</span></p>
<p><span class="math inline">\(X\)</span> has a mean (<span class="math inline">\(\alpha_X\)</span>) and variance (<span class="math inline">\(V(\epsilon_X)\)</span>).</p>
<p><span class="math inline">\(X\)</span> is an exogenous variable, so it’s intercept is it’s mean, and the residual captures all variance.</p>
<p><span class="math display">\[Y_i = \alpha_Y+ B_{21}X_i + \epsilon_{Yi}\]</span> <span class="math inline">\(Y\)</span> has a conditional mean (<span class="math inline">\(\alpha_Y + B_{21} X_i\)</span>) and a residual variance (<span class="math inline">\(V(\epsilon_Y)\)</span>)</p>
<p>This looks just like our regression equation, just with slightly different notation:</p>
<p><span class="math display">\[Y_i = b_0 + b_1 X_i + e_i\]</span></p>
</section>
<section id="fitting-sem-in-lavaan" class="level3">
<h3 class="anchored" data-anchor-id="fitting-sem-in-lavaan">Fitting SEM in <code>lavaan</code></h3>
<p>This is our first time using <code>lavaan</code> and we will add more details as we go, but I want you to see how we can fit the same model in an SEM</p>
<p><code>lavaan</code> uses a string input for the model, similar to the formula in lm (e.g., <code>internalizing_total~safe_avg</code>). But it is more complex, because SEM models can be more complex</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>SEMsimple <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="st">  # safe_avg (X) has an intercept</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="st">  safe_avg ~ 1</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="st">  # safe_avg (X) has a variance</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="st">  safe_avg ~~ safe_avg</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="st">  # internalizing_total (Y) mean structure</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="st">  internalizing_total ~ 1 + safe_avg</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="st">  # internalizing_total (Y) has residual variance</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="st">  internalizing_total ~~ internalizing_total</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Important notations:</p>
<ul>
<li><p><code>~</code> sets the mean structure (1 for intercept <code>+</code> predictor names)</p></li>
<li><p><code>~~</code> allows variables to covary with something… (itself or other variables)</p></li>
</ul>
</section>
<section id="fitting-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-model">Fitting Model</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>SEMsimple.fit <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(<span class="at">model =</span> SEMsimple, <span class="at">data =</span> ramos)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SEMsimple.fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 7 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         5

  Number of observations                           585

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                        Estimate  Std.Err  z-value  P(&gt;|z|)
  internalizing_total ~                                    
    safe_avg              10.927    0.901   12.124    0.000

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          1.508    0.018   82.586    0.000
   .internlzng_ttl   -0.970    1.416   -0.685    0.493

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          0.195    0.011   17.103    0.000
   .internlzng_ttl   92.628    5.416   17.103    0.000</code></pre>
</div>
</div>
<p>Let’s focus on two results:</p>
<ol type="1">
<li><span class="math inline">\(\hat{\alpha}_Y\)</span> = 0.19</li>
</ol>
<p>This is the same value that we got from the regression (<span class="math inline">\(\hat{b}_0\)</span>)</p>
<ol start="2" type="1">
<li><span class="math inline">\(\hat{B}_{21}\)</span> = 10.93</li>
</ol>
<p>This is the same value as the slope that we got from the regression (<span class="math inline">\(\hat{b}_1\)</span>)</p>
</section>
<section id="standard-errors" class="level3">
<h3 class="anchored" data-anchor-id="standard-errors">Standard Errors</h3>
<p>Compare the standard errors of these two estimates between the models.</p>
<p>What do you see?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 44%">
<col style="width: 25%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Estimate</th>
<th><span class="math inline">\(\hat{\alpha}_Y\)</span></th>
<th><span class="math inline">\(\hat{B}_{21}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS est.</td>
<td>-0.9697827</td>
<td>10.9268509</td>
</tr>
<tr class="even">
<td>SEM est.</td>
<td>-0.9697827</td>
<td>10.9268509</td>
</tr>
<tr class="odd">
<td>OLS SE</td>
<td>1.4181983</td>
<td>0.902833</td>
</tr>
<tr class="even">
<td>SEM SE</td>
<td>1.415772</td>
<td>0.9012884</td>
</tr>
</tbody>
</table>
<p>The estimate values are identical.</p>
<p>But for the standard errors, they are very similar, but differ somewhat.</p>
<p>This core difference is driven by SEMs using maximum likelihood estimation, rather than OLS.</p>
<p>We will discuss this more later.</p>
</section>
</section>
</section>
<section id="multiple-linear-regression" class="level1">
<h1>Multiple Linear Regression</h1>
<p>In a multiple regression we have multiple predictors predicting a single outcome.</p>
<p><span class="math display">\[Y_i = b_0 + \sum^K_{j = 1}b_k X_{ki} + \epsilon_i\]</span> Consider the example where we incorporate two control variables: <code>Age</code> and <code>Gender</code></p>
<section id="fitting-the-ols-regression" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-ols-regression">Fitting the OLS regression</h2>
<p><span class="math display">\[Y_i = b_0 + b_1 X_{1i}+b_2 X_{2i}+b_3 X_{3i} + \epsilon_i\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>OLSmulti <span class="ot">&lt;-</span> <span class="fu">lm</span>(internalizing_total <span class="sc">~</span> safe_avg<span class="sc">+</span>Age<span class="sc">+</span>Gender, <span class="at">data =</span> ramos)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(OLSmulti)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = internalizing_total ~ safe_avg + Age + Gender, data = ramos)

Residuals:
    Min      1Q  Median      3Q     Max 
-25.620  -6.457  -1.142   5.005  30.368 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -6.94697    5.20997  -1.333    0.183    
safe_avg    10.33029    0.87749  11.773  &lt; 2e-16 ***
Age         -0.05838    0.31453  -0.186    0.853    
Gender       5.12476    0.77501   6.613 8.57e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.313 on 581 degrees of freedom
Multiple R-squared:  0.2568,    Adjusted R-squared:  0.253 
F-statistic: 66.92 on 3 and 581 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>For now, let’s focus on the estimated relationship between discrimination and internalizing: 10.33</p>
</section>
<section id="how-to-express-the-sem" class="level2">
<h2 class="anchored" data-anchor-id="how-to-express-the-sem">How to express the SEM</h2>
<p>Our simplified SEM equation is</p>
<p><span class="math display">\[ \bf Z = \alpha + BZ + \epsilon\]</span></p>
<p>Where <span class="math inline">\({\bf Z} = \begin{bmatrix} {\bf X} \\ Y \end{bmatrix}\)</span></p>
<p>Now <span class="math inline">\(\bf X\)</span> has three elements <span class="math inline">\(X_1\)</span> (discrimination), <span class="math inline">\(X_2\)</span> (age), and <span class="math inline">\(X_3\)</span> (gender).</p>
<p><span class="math inline">\(\bf B\)</span> also looks different because of the change in the predictors</p>
<p><span class="math display">\[{\bf B} = \begin{bmatrix} 0 &amp; 0 &amp; 0 &amp; 0\\ 0 &amp; 0 &amp; 0 &amp; 0\\ 0 &amp; 0 &amp; 0 &amp; 0\\1 &amp; 1 &amp; 1 &amp; 0 \end{bmatrix}\]</span></p>
<p>No <span class="math inline">\(X\)</span> variables predict each other, but all <span class="math inline">\(X\)</span>s predict <span class="math inline">\(Y\)</span>.</p>
</section>
<section id="how-to-specify-in-lavaan" class="level2">
<h2 class="anchored" data-anchor-id="how-to-specify-in-lavaan">How to specify in lavaan</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>SEMmulti <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="st">  # safe_avg (X1) has an intercept</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="st">  safe_avg ~ 1</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="st">  # safe_avg (X1) has a variance</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="st">  safe_avg ~~ safe_avg</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="st">  # Age (X2) has an intercept</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="st">  Age ~ 1</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="st">  # Age (X2) has a variance</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="st">  Age ~~ Age</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="st">  # Gender (X3) has an intercept</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="st">  Gender ~ 1</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="st">  # Gender (X3) has a variance</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="st">  Gender ~~ Gender</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a><span class="st">  # internalizing_total (Y) mean structure</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="st">  internalizing_total ~ 1 + safe_avg+Age+Gender</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a><span class="st">  # internalizing_total (Y) has residual variance</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="st">  internalizing_total ~~ internalizing_total</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="fit-the-model-in-lavaan" class="level2">
<h2 class="anchored" data-anchor-id="fit-the-model-in-lavaan">Fit the model in lavaan</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>SEMmulti.fit <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(<span class="at">model =</span> SEMmulti, <span class="at">data =</span> ramos)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SEMmulti.fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 13 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        11

  Number of observations                           585

Model Test User Model:
                                                      
  Test statistic                                 7.192
  Degrees of freedom                                 3
  P-value (Chi-square)                           0.066

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                        Estimate  Std.Err  z-value  P(&gt;|z|)
  internalizing_total ~                                    
    safe_avg              10.330    0.869   11.886    0.000
    Age                   -0.058    0.313   -0.186    0.852
    Gender                 5.125    0.768    6.672    0.000

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          1.508    0.018   82.586    0.000
    Age              15.762    0.051  311.199    0.000
    Gender            1.521    0.021   73.661    0.000
   .internlzng_ttl   -6.947    5.254   -1.322    0.186

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          0.195    0.011   17.103    0.000
    Age               1.501    0.088   17.103    0.000
    Gender            0.250    0.015   17.103    0.000
   .internlzng_ttl   86.137    5.036   17.103    0.000</code></pre>
</div>
</div>
<p>As before the coefficient estimates match those from the OLS.</p>
<p>The standard errors are different but only slightly.</p>
</section>
</section>
<section id="multivariate-linear-regression" class="level1">
<h1>Multivariate Linear Regression</h1>
<p>Multivariate linear regression is when we have multiple linear regression equations, predicting different outcomes. These may or may not have the same set of predictors, and the outcome in one equation may also be a predictor in another equation.</p>
<p>For today, let’s keep it simple. We will predict internalizing symptoms and familism using the same predictors: discrimination, age, and gender.</p>
<section id="the-equations" class="level2">
<h2 class="anchored" data-anchor-id="the-equations">The equations</h2>
<p><span class="math display">\[Y_{1i} = \alpha_{Y_1} + b_{11} X_{1i}+b_{12} X_{2i}+b_{13} X_{3i} + \epsilon_{Y_{1i}}\]</span></p>
<p><span class="math display">\[Y_{2i} = \alpha_{Y_2} + b_{21} X_{1i}+b_{22} X_{2i}+b_{23} X_{3i} + \epsilon_{Y_{2i}}\]</span></p>
<p><span class="math inline">\(Y_1\)</span> is internalizing symptoms <span class="math inline">\(Y_2\)</span> is Familism</p>
</section>
<section id="fitting-this-model-with-ols" class="level2">
<h2 class="anchored" data-anchor-id="fitting-this-model-with-ols">Fitting this model with OLS</h2>
<p>In an OLS context we would fit these two equations separately</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>OLSmvInt <span class="ot">&lt;-</span> <span class="fu">lm</span>(internalizing_total<span class="sc">~</span>safe_avg<span class="sc">+</span>Age<span class="sc">+</span>Gender, <span class="at">data =</span> ramos)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(OLSmvInt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = internalizing_total ~ safe_avg + Age + Gender, data = ramos)

Residuals:
    Min      1Q  Median      3Q     Max 
-25.620  -6.457  -1.142   5.005  30.368 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -6.94697    5.20997  -1.333    0.183    
safe_avg    10.33029    0.87749  11.773  &lt; 2e-16 ***
Age         -0.05838    0.31453  -0.186    0.853    
Gender       5.12476    0.77501   6.613 8.57e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.313 on 581 degrees of freedom
Multiple R-squared:  0.2568,    Adjusted R-squared:  0.253 
F-statistic: 66.92 on 3 and 581 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Note that this model is the same as what we just estimated in the previous section</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>OLSmvFam <span class="ot">&lt;-</span> <span class="fu">lm</span>(FStot<span class="sc">~</span>safe_avg<span class="sc">+</span>Age<span class="sc">+</span>Gender, <span class="at">data =</span> ramos)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(OLSmvFam)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FStot ~ safe_avg + Age + Gender, data = ramos)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.708  -3.105   0.328   4.274  11.804 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  38.6296     3.0247  12.771  &lt; 2e-16 ***
safe_avg     -3.9175     0.5094  -7.690 6.33e-14 ***
Age          -0.1674     0.1826  -0.917 0.359643    
Gender       -1.5291     0.4499  -3.398 0.000724 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.407 on 581 degrees of freedom
Multiple R-squared:  0.1189,    Adjusted R-squared:  0.1143 
F-statistic: 26.12 on 3 and 581 DF,  p-value: 7.291e-16</code></pre>
</div>
</div>
</section>
<section id="fitting-the-sem" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-sem">Fitting the SEM</h2>
<p>Create a script with the information about <code>FStot</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>SEMmulti.fam <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="st">  # FStot (Y2) mean structure</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="st">  FStot ~ 1 + safe_avg+Age+Gender</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="st">  # FStot (Y2) has residual variance</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="st">  FStot ~~ FStot</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>lavaan</code> has a cool feature where you can combine two syntaxes</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>SEMmv.fit <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(<span class="at">model =</span> <span class="fu">c</span>(SEMmulti,SEMmulti.fam), <span class="at">data =</span> ramos)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SEMmv.fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 18 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        16

  Number of observations                           585

Model Test User Model:
                                                      
  Test statistic                                99.818
  Degrees of freedom                                 4
  P-value (Chi-square)                           0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                        Estimate  Std.Err  z-value  P(&gt;|z|)
  internalizing_total ~                                    
    safe_avg              10.330    0.869   11.886    0.000
    Age                   -0.058    0.313   -0.186    0.852
    Gender                 5.125    0.768    6.672    0.000
  FStot ~                                                  
    safe_avg              -3.917    0.505   -7.764    0.000
    Age                   -0.167    0.182   -0.921    0.357
    Gender                -1.529    0.446   -3.429    0.001

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          1.508    0.018   82.586    0.000
    Age              15.762    0.051  311.199    0.000
    Gender            1.521    0.021   73.661    0.000
   .internlzng_ttl   -6.947    5.254   -1.322    0.186
   .FStot            38.630    3.050   12.664    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          0.195    0.011   17.103    0.000
    Age               1.501    0.088   17.103    0.000
    Gender            0.250    0.015   17.103    0.000
   .internlzng_ttl   86.137    5.036   17.103    0.000
   .FStot            29.032    1.698   17.103    0.000</code></pre>
</div>
</div>
<p>Notice that the values are not quite the same as the OLS.</p>
<p>What’s going on here? Any ideas?</p>
<section id="explicit-parameters" class="level3">
<h3 class="anchored" data-anchor-id="explicit-parameters">Explicit Parameters</h3>
<p>Many people might assume that because OLS estimates the two regression separately, that <span class="math inline">\(e_{Y_{1}}\)</span> and <span class="math inline">\(e_{Y_2}\)</span> are independent.</p>
<p>But this is actually not the case. Estimating the models separately allows the residuals to covary freely.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">resid</span>(OLSmvInt),<span class="fu">resid</span>(OLSmvFam))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.3826705</code></pre>
</div>
</div>
<p>In the OLS models, people with higher residuals on Internalizing Symptoms tend to have lower residuals on Familism</p>
<p>But in the SEM model, we did not explicitly allow for that correlation (and so it is assumed to be zero)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavInspect</span>(SEMmv.fit, <span class="st">"theta"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    intrn_  FStot saf_vg    Age Gender
internalizing_total 86.137                            
FStot                0.000 29.032                     
safe_avg             0.000  0.000  0.195              
Age                  0.000  0.000  0.000  1.501       
Gender               0.000  0.000  0.000  0.000  0.250</code></pre>
</div>
</div>
<p>SEM software is very literal! If you don’t include a parameter it will not be included by <code>lavaan</code>.</p>
<p>Let’s try adding this residual correlation</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>resid.cor <span class="ot">&lt;-</span> <span class="st">"internalizing_total~~FStot"</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>SEMmvcr.fit <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(<span class="at">model =</span> <span class="fu">c</span>(SEMmulti,SEMmulti.fam, resid.cor), <span class="at">data =</span> ramos)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SEMmvcr.fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 62 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        17

  Number of observations                           585

Model Test User Model:
                                                      
  Test statistic                                 7.192
  Degrees of freedom                                 3
  P-value (Chi-square)                           0.066

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                        Estimate  Std.Err  z-value  P(&gt;|z|)
  internalizing_total ~                                    
    safe_avg              10.330    0.869   11.886    0.000
    Age                   -0.058    0.313   -0.187    0.852
    Gender                 5.125    0.768    6.672    0.000
  FStot ~                                                  
    safe_avg              -3.917    0.505   -7.764    0.000
    Age                   -0.167    0.182   -0.921    0.357
    Gender                -1.529    0.446   -3.429    0.001

Covariances:
                         Estimate  Std.Err  z-value  P(&gt;|z|)
 .internalizing_total ~~                                    
   .FStot                 -19.136    2.214   -8.644    0.000

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          1.508    0.018   82.586    0.000
    Age              15.762    0.051  311.199    0.000
    Gender            1.521    0.021   73.661    0.000
   .internlzng_ttl   -6.946    5.254   -1.322    0.186
   .FStot            38.629    3.050   12.664    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          0.195    0.011   17.103    0.000
    Age               1.501    0.088   17.103    0.000
    Gender            0.250    0.015   17.103    0.000
   .internlzng_ttl   86.137    5.036   17.103    0.000
   .FStot            29.032    1.698   17.103    0.000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>OLSmvFam</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FStot ~ safe_avg + Age + Gender, data = ramos)

Coefficients:
(Intercept)     safe_avg          Age       Gender  
    38.6296      -3.9175      -0.1674      -1.5291  </code></pre>
</div>
</div>
<p>Now everything matches up. We can also look at the residual correlation matrix:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavInspect</span>(SEMmvcr.fit, <span class="st">"theta"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     intrn_   FStot  saf_vg     Age  Gender
internalizing_total  86.137                                
FStot               -19.136  29.032                        
safe_avg              0.000   0.000   0.195                
Age                   0.000   0.000   0.000   1.501        
Gender                0.000   0.000   0.000   0.000   0.250</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov2cor</span>(<span class="fu">lavInspect</span>(SEMmvcr.fit, <span class="st">"theta"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    intrn_  FStot saf_vg    Age Gender
internalizing_total  1.000                            
FStot               -0.383  1.000                     
safe_avg             0.000  0.000  1.000              
Age                  0.000  0.000  0.000  1.000       
Gender               0.000  0.000  0.000  0.000  1.000</code></pre>
</div>
</div>
<p>The SEM estimation of the correlated residuals is very similar to the correlation calculated from the OLS.</p>
<p>But OLS does not estimate this correlation directly, and thus cannot test hypotheses about this correlation.</p>
<p>What if we wanted to know whether this correlation was similar to zero or not? OLS cannot tell us directly.</p>
<p>This explicit modeling of all parameters is an advantage of SEM!</p>
</section>
</section>
</section>
<section id="benefits-of-sem-in-these-contexts" class="level1">
<h1>Benefits of SEM in these contexts?</h1>
<p>So, if SEM and OLS regression do essentially the same thing. Why does it matter which one we use?</p>
<p>Actually, in many circumstances you can use either OLS or SEM and both are equally valuable.</p>
<p>But, even in these simple regression cases, there are some advantages to SEM that we can see.</p>
<section id="missing-data" class="level2">
<h2 class="anchored" data-anchor-id="missing-data">Missing Data</h2>
<p>OLS regression uses listwise deletion. If a case is missing on any variable involved, that case is not included in the analysis.</p>
<p>The Ramos data does actually have some missingness that we’ve ignored so far</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>ramos.missing <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Ramos_Internalizing.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>How many cases are there now?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ramos)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 585  60</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ramos.missing)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 676  60</code></pre>
</div>
</div>
<p>Almost 100 more cases in the data with “missingness”</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(ramos.missing, <span class="fu">all_of</span>(<span class="fu">c</span>(<span class="st">"Age"</span>, <span class="st">"Gender"</span>, <span class="st">"safe_avg"</span>, <span class="st">"FStot"</span>, <span class="st">"internalizing_total"</span>))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age            Gender         safe_avg         FStot      
 Min.   :13.00   Min.   :1.000   Min.   :1.000   Min.   : 8.00  
 1st Qu.:15.00   1st Qu.:1.000   1st Qu.:1.222   1st Qu.:24.00  
 Median :16.00   Median :2.000   Median :1.444   Median :28.00  
 Mean   :15.74   Mean   :1.525   Mean   :1.513   Mean   :27.53  
 3rd Qu.:17.00   3rd Qu.:2.000   3rd Qu.:1.667   3rd Qu.:32.00  
 Max.   :19.00   Max.   :2.000   Max.   :3.778   Max.   :35.00  
                                 NA's   :66      NA's   :30     
 internalizing_total
 Min.   : 0.0       
 1st Qu.: 7.0       
 Median :14.0       
 Mean   :15.6       
 3rd Qu.:22.0       
 Max.   :55.0       
 NA's   :33         </code></pre>
</div>
</div>
<p>Many cases are missing on at least some of the variables.</p>
<p>What happens if we fit the OLS regressions:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>OLSmvInt.miss <span class="ot">&lt;-</span> <span class="fu">lm</span>(internalizing_total<span class="sc">~</span>Age<span class="sc">+</span>Gender<span class="sc">+</span>safe_avg, <span class="at">data =</span> ramos.missing)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(OLSmvInt.miss)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = internalizing_total ~ Age + Gender + safe_avg, data = ramos.missing)

Residuals:
    Min      1Q  Median      3Q     Max 
-25.218  -6.627  -1.085   4.985  30.450 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -7.39283    5.19064  -1.424    0.155    
Age         -0.02645    0.31315  -0.084    0.933    
Gender       5.17322    0.77046   6.714 4.45e-11 ***
safe_avg    10.16621    0.87303  11.645  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.324 on 589 degrees of freedom
  (83 observations deleted due to missingness)
Multiple R-squared:  0.2524,    Adjusted R-squared:  0.2486 
F-statistic: 66.29 on 3 and 589 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>OLSmvFam.miss <span class="ot">&lt;-</span> <span class="fu">lm</span>(FStot<span class="sc">~</span>Age<span class="sc">+</span>Gender<span class="sc">+</span>safe_avg, <span class="at">data =</span> ramos.missing)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(OLSmvFam.miss)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FStot ~ Age + Gender + safe_avg, data = ramos.missing)

Residuals:
     Min       1Q   Median       3Q      Max 
-18.7012  -3.1256   0.3113   4.3019  11.6766 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  38.0363     2.9845  12.745  &lt; 2e-16 ***
Age          -0.1512     0.1801  -0.840  0.40144    
Gender       -1.4118     0.4439  -3.180  0.00155 ** 
safe_avg     -3.8192     0.5024  -7.603 1.13e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.4 on 596 degrees of freedom
  (76 observations deleted due to missingness)
Multiple R-squared:  0.112, Adjusted R-squared:  0.1075 
F-statistic: 25.05 on 3 and 596 DF,  p-value: 2.83e-15</code></pre>
</div>
</div>
<p>The two models are based on somewhat different samples.</p>
<p>Compare this to SEM</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>SEMmv.fit.miss <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(<span class="at">model =</span> <span class="fu">c</span>(SEMmulti,SEMmulti.fam, resid.cor), <span class="at">data =</span> ramos.missing)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SEMmv.fit.miss)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 62 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        17

                                                  Used       Total
  Number of observations                           585         676

Model Test User Model:
                                                      
  Test statistic                                 7.192
  Degrees of freedom                                 3
  P-value (Chi-square)                           0.066

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                        Estimate  Std.Err  z-value  P(&gt;|z|)
  internalizing_total ~                                    
    safe_avg              10.330    0.869   11.886    0.000
    Age                   -0.058    0.313   -0.187    0.852
    Gender                 5.125    0.768    6.672    0.000
  FStot ~                                                  
    safe_avg              -3.917    0.505   -7.764    0.000
    Age                   -0.167    0.182   -0.921    0.357
    Gender                -1.529    0.446   -3.429    0.001

Covariances:
                         Estimate  Std.Err  z-value  P(&gt;|z|)
 .internalizing_total ~~                                    
   .FStot                 -19.136    2.214   -8.644    0.000

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          1.508    0.018   82.586    0.000
    Age              15.762    0.051  311.199    0.000
    Gender            1.521    0.021   73.661    0.000
   .internlzng_ttl   -6.946    5.254   -1.322    0.186
   .FStot            38.629    3.050   12.664    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          0.195    0.011   17.103    0.000
    Age               1.501    0.088   17.103    0.000
    Gender            0.250    0.015   17.103    0.000
   .internlzng_ttl   86.137    5.036   17.103    0.000
   .FStot            29.032    1.698   17.103    0.000</code></pre>
</div>
</div>
<p>Default model uses only cases with complete data, which ends up being even smaller than OLS samples. This on it’s own is not ideal.</p>
<p>But there are options in SEM that are not available in OLS. Full information maximum likelihood (FIML) can be used when estimating the model to take advantage of the data that is available.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>SEMmv.fit.fiml <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(<span class="at">model =</span> <span class="fu">c</span>(SEMmulti,SEMmulti.fam, resid.cor), <span class="at">data =</span> ramos.missing, <span class="at">missing =</span> <span class="st">"ML"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SEMmv.fit.fiml)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 72 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        17

  Number of observations                           676
  Number of missing patterns                         8

Model Test User Model:
                                                      
  Test statistic                                 7.991
  Degrees of freedom                                 3
  P-value (Chi-square)                           0.046

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Observed
  Observed information based on                Hessian

Regressions:
                        Estimate  Std.Err  z-value  P(&gt;|z|)
  internalizing_total ~                                    
    safe_avg              10.224    0.871   11.736    0.000
    Age                   -0.107    0.308   -0.346    0.729
    Gender                 5.422    0.750    7.233    0.000
  FStot ~                                                  
    safe_avg              -3.866    0.517   -7.480    0.000
    Age                   -0.107    0.180   -0.594    0.552
    Gender                -1.196    0.437   -2.735    0.006

Covariances:
                         Estimate  Std.Err  z-value  P(&gt;|z|)
 .internalizing_total ~~                                    
   .FStot                 -18.641    2.224   -8.380    0.000

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          1.518    0.018   85.504    0.000
    Age              15.741    0.046  341.013    0.000
    Gender            1.525    0.019   79.408    0.000
   .internlzng_ttl   -6.457    5.117   -1.262    0.207
   .FStot            36.923    2.988   12.358    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          0.195    0.011   17.440    0.000
    Age               1.440    0.078   18.385    0.000
    Gender            0.249    0.014   18.385    0.000
   .internlzng_ttl   88.031    5.002   17.600    0.000
   .FStot            30.376    1.708   17.785    0.000</code></pre>
</div>
</div>
<p>Now, all cases are used (676), but only contribute to relevant parts of the model they have data for.</p>
<p>More on missing data later in the course.</p>
</section>
<section id="model-constraints" class="level2">
<h2 class="anchored" data-anchor-id="model-constraints">Model Constraints</h2>
<p>Another feature available in SEM that is not in OLS, is the ability to constrain parameters.</p>
<p>There are multiple kinds of constraints one could consider: - Value constraints (force a parameter to be exactly a value) - Equality constraints (force two parameters to be equal in value)</p>
<section id="value-constraints" class="level3">
<h3 class="anchored" data-anchor-id="value-constraints">Value constraints</h3>
<p>Imagine I know, based on the way we collected the data that Age and Gender are uncorrelated.</p>
<p>I can force their correlation to be exactly zero in the model (we cannot do this in regression)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>AG0 <span class="ot">&lt;-</span> <span class="st">"Age ~~0*Gender"</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>SEMmv.fit.AG0 <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(<span class="at">model =</span> <span class="fu">c</span>(SEMmulti,SEMmulti.fam, resid.cor, AG0), <span class="at">data =</span> ramos.missing, <span class="at">missing =</span> <span class="st">"ML"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SEMmv.fit.AG0)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 72 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        17

  Number of observations                           676
  Number of missing patterns                         8

Model Test User Model:
                                                      
  Test statistic                                 7.991
  Degrees of freedom                                 3
  P-value (Chi-square)                           0.046

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Observed
  Observed information based on                Hessian

Regressions:
                        Estimate  Std.Err  z-value  P(&gt;|z|)
  internalizing_total ~                                    
    safe_avg              10.224    0.871   11.736    0.000
    Age                   -0.107    0.308   -0.346    0.729
    Gender                 5.422    0.750    7.233    0.000
  FStot ~                                                  
    safe_avg              -3.866    0.517   -7.480    0.000
    Age                   -0.107    0.180   -0.594    0.552
    Gender                -1.196    0.437   -2.735    0.006

Covariances:
                         Estimate  Std.Err  z-value  P(&gt;|z|)
 .internalizing_total ~~                                    
   .FStot                 -18.641    2.224   -8.380    0.000
  Age ~~                                                    
    Gender                  0.000                           

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          1.518    0.018   85.504    0.000
    Age              15.741    0.046  341.013    0.000
    Gender            1.525    0.019   79.408    0.000
   .internlzng_ttl   -6.457    5.117   -1.262    0.207
   .FStot            36.923    2.988   12.358    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          0.195    0.011   17.440    0.000
    Age               1.440    0.078   18.385    0.000
    Gender            0.249    0.014   18.385    0.000
   .internlzng_ttl   88.031    5.002   17.600    0.000
   .FStot            30.376    1.708   17.785    0.000</code></pre>
</div>
</div>
<p>This changes the other estimates in the model, but as long as this restriction is accurate, it should improve the model.</p>
</section>
<section id="equality-constraints" class="level3">
<h3 class="anchored" data-anchor-id="equality-constraints">Equality Constraints</h3>
<p>Older kids tend to show less internalizing and less familism.</p>
<p>I could force the slope for Age to each endogenous variable to be equal in an SEM.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>SEMconstraint <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="st">  # safe_avg (X1) has an intercept</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="st">  safe_avg ~ 1</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="st">  # safe_avg (X1) has a variance</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="st">  safe_avg ~~ safe_avg</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="st">  # Age (X2) has an intercept</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="st">  Age ~ 1</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="st">  # Age (X2) has a variance</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a><span class="st">  Age ~~ Age</span></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a><span class="st">  # Gender (X3) has an intercept</span></span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a><span class="st">  Gender ~ 1</span></span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a><span class="st">  # Gender (X3) has a variance</span></span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a><span class="st">  Gender ~~ Gender</span></span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a><span class="st">  # internalizing_total (Y1) mean structure</span></span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a><span class="st">  internalizing_total ~ 1 + safe_avg+bage*Age+Gender</span></span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb56-23"><a href="#cb56-23" aria-hidden="true" tabindex="-1"></a><span class="st">  # internalizing_total (Y1) has residual variance</span></span>
<span id="cb56-24"><a href="#cb56-24" aria-hidden="true" tabindex="-1"></a><span class="st">  internalizing_total ~~ internalizing_total</span></span>
<span id="cb56-25"><a href="#cb56-25" aria-hidden="true" tabindex="-1"></a><span class="st">    </span></span>
<span id="cb56-26"><a href="#cb56-26" aria-hidden="true" tabindex="-1"></a><span class="st">  # FStot (Y2) mean structure</span></span>
<span id="cb56-27"><a href="#cb56-27" aria-hidden="true" tabindex="-1"></a><span class="st">  FStot ~ 1 + safe_avg+bage*Age+Gender</span></span>
<span id="cb56-28"><a href="#cb56-28" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb56-29"><a href="#cb56-29" aria-hidden="true" tabindex="-1"></a><span class="st">  # FStot (Y2) has residual variance</span></span>
<span id="cb56-30"><a href="#cb56-30" aria-hidden="true" tabindex="-1"></a><span class="st">  FStot ~~ FStot</span></span>
<span id="cb56-31"><a href="#cb56-31" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb56-32"><a href="#cb56-32" aria-hidden="true" tabindex="-1"></a><span class="st">  # correlated errors</span></span>
<span id="cb56-33"><a href="#cb56-33" aria-hidden="true" tabindex="-1"></a><span class="st">  FStot ~~ internalizing_total</span></span>
<span id="cb56-34"><a href="#cb56-34" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb56-35"><a href="#cb56-35" aria-hidden="true" tabindex="-1"></a>SEMconstraint.fit <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(SEMconstraint, <span class="at">data =</span> ramos.missing, <span class="at">missing =</span> <span class="st">"ML"</span>)</span>
<span id="cb56-36"><a href="#cb56-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-37"><a href="#cb56-37" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SEMconstraint.fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 62 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        17
  Number of equality constraints                     1

  Number of observations                           676
  Number of missing patterns                         8

Model Test User Model:
                                                      
  Test statistic                                 7.991
  Degrees of freedom                                 4
  P-value (Chi-square)                           0.092

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Observed
  Observed information based on                Hessian

Regressions:
                        Estimate  Std.Err  z-value  P(&gt;|z|)
  internalizing_total ~                                    
    safe_vg               10.224    0.871   11.740    0.000
    Age     (bage)        -0.107    0.127   -0.843    0.399
    Gender                 5.422    0.750    7.234    0.000
  FStot ~                                                  
    safe_vg               -3.866    0.517   -7.481    0.000
    Age     (bage)        -0.107    0.127   -0.843    0.399
    Gender                -1.196    0.437   -2.735    0.006

Covariances:
                         Estimate  Std.Err  z-value  P(&gt;|z|)
 .internalizing_total ~~                                    
   .FStot                 -18.641    2.224   -8.380    0.000

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          1.518    0.018   85.505    0.000
    Age              15.741    0.046  341.013    0.000
    Gender            1.525    0.019   79.408    0.000
   .internlzng_ttl   -6.455    2.605   -2.478    0.013
   .FStot            36.922    2.220   16.632    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          0.195    0.011   17.440    0.000
    Age               1.440    0.078   18.385    0.000
    Gender            0.249    0.014   18.385    0.000
   .internlzng_ttl   88.031    5.002   17.600    0.000
   .FStot            30.376    1.708   17.785    0.000</code></pre>
</div>
</div>
<p>So long as this constraint is accurate it simplifies the model.</p>
</section>
</section>
<section id="testing-model-parameters" class="level2">
<h2 class="anchored" data-anchor-id="testing-model-parameters">Testing Model Parameters</h2>
<p>Perhaps instead of forcing the path from Age to each outcome to be equal, I want to test their difference.</p>
<p>I can also do this in an SEM</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>SEMtest <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="st">  # safe_avg (X1) has an intercept</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="st">  safe_avg ~ 1</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="st">  # safe_avg (X1) has a variance</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="st">  safe_avg ~~ safe_avg</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="st">  # Age (X2) has an intercept</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="st">  Age ~ 1</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a><span class="st">  # Age (X2) has a variance</span></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a><span class="st">  Age ~~ Age</span></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a><span class="st">  # Gender (X3) has an intercept</span></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a><span class="st">  Gender ~ 1</span></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a><span class="st">  # Gender (X3) has a variance</span></span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a><span class="st">  Gender ~~ Gender</span></span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a><span class="st">  # internalizing_total (Y1) mean structure</span></span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a><span class="st">  internalizing_total ~ 1 + safe_avg+bage.int*Age+Gender</span></span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a><span class="st">  # internalizing_total (Y1) has residual variance</span></span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a><span class="st">  internalizing_total ~~ internalizing_total</span></span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a><span class="st">    </span></span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a><span class="st">  # FStot (Y2) mean structure</span></span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a><span class="st">  FStot ~ 1 + safe_avg+bage.fs*Age+Gender</span></span>
<span id="cb58-28"><a href="#cb58-28" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb58-29"><a href="#cb58-29" aria-hidden="true" tabindex="-1"></a><span class="st">  # FStot (Y2) has residual variance</span></span>
<span id="cb58-30"><a href="#cb58-30" aria-hidden="true" tabindex="-1"></a><span class="st">  FStot ~~ FStot</span></span>
<span id="cb58-31"><a href="#cb58-31" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb58-32"><a href="#cb58-32" aria-hidden="true" tabindex="-1"></a><span class="st">  # correlated errors</span></span>
<span id="cb58-33"><a href="#cb58-33" aria-hidden="true" tabindex="-1"></a><span class="st">  FStot ~~ internalizing_total</span></span>
<span id="cb58-34"><a href="#cb58-34" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb58-35"><a href="#cb58-35" aria-hidden="true" tabindex="-1"></a><span class="st">  bage.diff := bage.int-bage.fs</span></span>
<span id="cb58-36"><a href="#cb58-36" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb58-37"><a href="#cb58-37" aria-hidden="true" tabindex="-1"></a>SEMtest.fit <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(SEMtest, <span class="at">data =</span> ramos.missing, <span class="at">missing =</span> <span class="st">"ML"</span>)</span>
<span id="cb58-38"><a href="#cb58-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-39"><a href="#cb58-39" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SEMtest.fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 72 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        17

  Number of observations                           676
  Number of missing patterns                         8

Model Test User Model:
                                                      
  Test statistic                                 7.991
  Degrees of freedom                                 3
  P-value (Chi-square)                           0.046

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Observed
  Observed information based on                Hessian

Regressions:
                        Estimate  Std.Err  z-value  P(&gt;|z|)
  internalizing_total ~                                    
    safe_vg               10.224    0.871   11.736    0.000
    Age     (bg.n)        -0.107    0.308   -0.346    0.729
    Gender                 5.422    0.750    7.233    0.000
  FStot ~                                                  
    safe_vg               -3.866    0.517   -7.480    0.000
    Age     (bg.f)        -0.107    0.180   -0.594    0.552
    Gender                -1.196    0.437   -2.735    0.006

Covariances:
                         Estimate  Std.Err  z-value  P(&gt;|z|)
 .internalizing_total ~~                                    
   .FStot                 -18.641    2.224   -8.380    0.000

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          1.518    0.018   85.504    0.000
    Age              15.741    0.046  341.013    0.000
    Gender            1.525    0.019   79.408    0.000
   .internlzng_ttl   -6.457    5.117   -1.262    0.207
   .FStot            36.923    2.988   12.358    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    safe_avg          0.195    0.011   17.440    0.000
    Age               1.440    0.078   18.385    0.000
    Gender            0.249    0.014   18.385    0.000
   .internlzng_ttl   88.031    5.002   17.600    0.000
   .FStot            30.376    1.708   17.785    0.000

Defined Parameters:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
    bage.diff         0.000    0.408    0.000    1.000</code></pre>
</div>
</div>
<p>There is not a significant difference between the two age slopes!</p>
</section>
<section id="but-beware" class="level2">
<h2 class="anchored" data-anchor-id="but-beware">But Beware!</h2>
<p>While SEM makes it very easy to do many different things, we have to be thoughtful and theory driven in our choices.</p>
<p>We cannot “double dip” in our models, constantly respecifying until we get something that “looks publishable”.</p>
<p>For example, it would not be appropriate to look at the unconstrained model, observe the similarity, test the constraint, then add the constraint, if there’s no theoretical reason to suggest these paths are equal.</p>
<p>Otherwise we are just capitalizing on chance.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>